[package]
name = "jedi"
version = "0.1.0"
authors = ["Andrew Danger Lyon <orthecreedence@gmail.com>"]

[lib]
doctest = false				# these annoy me

[dependencies]
quick-error = "1.1.0"
serde = "1.0.8"
serde_json = "1.0.2"
serde_yaml = "0.7.1"

